# Generated by Django 5.1.5 on 2025-02-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='meme',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='meme',
            old_name='timestamp',
            new_name='uploaded_at',
        ),
        migrations.RenameField(
            model_name='meme',
            old_name='usuario',
            new_name='user',
        ),
    ]
