# Generated by Django 5.1.5 on 2025-02-05 05:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_rename_descripcion_meme_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('confianza', models.PositiveIntegerField(blank=True, null=True)),
                ('meme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memes', to='memes.meme')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['tag'],
                'indexes': [models.Index(fields=['tag'], name='memes_tag_tag_88a84c_idx')],
            },
        ),
    ]
