# Generated by Django 5.1.5 on 2025-02-06 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='meme_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='memes.meme'),
        ),
    ]
