# Generated by Django 5.1.5 on 2025-02-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0005_alter_tag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
