# Generated by Django 5.1.5 on 2025-02-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0006_alter_tag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='confianza',
            field=models.TextField(blank=True, null=True),
        ),
    ]
